### ISSUE TITLE
Package using old Riot logo

### ISSUE THREAD

**Issue by starcraft66** [taw00/riot-rpm#23]
The riot logo should be updated to the new blue variant.

https://github.com/vector-im/riot-web/blob/develop/electron_app/img/riot.ico

**Comment by taw00** [comment]
You are correct. It will take awhile since I have to create all the bit varieties. Not a priority, but I will get to it.

**Comment by taw00** [comment]
Done! `sudo dnf upgrade` :)

**Comment by domrim** [comment]
Running fedora 30. I still have the old icon in the gnome application menu.
Is this a bug? Or did something mess up?

**Comment by domrim** [comment]
> Running fedora 30. I still have the old icon in the gnome application menu.
> Is this a bug? Or did something mess up?

Nvmd. had an old icon-set activated.
